version: 1.9.alpha.{build}


init:
  - cinst autoit.commandline

build: off

test_script:
  - git submodule update --init
  - cd tests
  - autoit3 /ErrorStdOut /AutoIt3ExecuteScript imperius.tests.au3 ci
